using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using CrlMonitor.Models;
using CrlMonitor.Reporting;
using CrlMonitor.State;

namespace CrlMonitor.Notifications;

internal sealed class EmailReportReporter : IReporter
{
    private readonly ReportOptions _options;
    private readonly IEmailClient _emailClient;
    private readonly IStateStore _stateStore;
    private readonly ReportingStatus _reportingStatus;
    private readonly string? _htmlReportUrl;

    public EmailReportReporter(ReportOptions options, IEmailClient emailClient, IStateStore stateStore, ReportingStatus reportingStatus, string? htmlReportUrl)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
        _emailClient = emailClient ?? throw new ArgumentNullException(nameof(emailClient));
        _stateStore = stateStore ?? throw new ArgumentNullException(nameof(stateStore));
        _reportingStatus = reportingStatus ?? throw new ArgumentNullException(nameof(reportingStatus));
        _htmlReportUrl = htmlReportUrl;
    }

    public async Task ReportAsync(CrlCheckRun run, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(run);
        if (!_options.Enabled)
        {
            return;
        }

        var summary = BuildSummary(run);
        var subject = BuildSubject(_options.Subject, summary.Errors);
        var plainBody = BuildPlainTextBody(run, _options, summary);
        var htmlBody = BuildHtmlBody(run, _options, summary);
        var attachments = new List<EmailAttachment>();
        if (_options.IncludeFullCsv)
        {
            var csvBytes = await BuildCsvAttachmentAsync(run, cancellationToken).ConfigureAwait(false);
            attachments.Add(new EmailAttachment(BuildAttachmentName(run.GeneratedAtUtc), csvBytes, "text/csv"));
        }

        var plain = AppendHtmlLinkPlain(plainBody, _htmlReportUrl);
        var html = AppendHtmlLinkHtml(htmlBody, _htmlReportUrl);
        var message = new EmailMessage(_options.Recipients, subject, plain, attachments, html);
        await _emailClient.SendAsync(message, _options.Smtp, cancellationToken).ConfigureAwait(false);
        _reportingStatus.RecordEmailSent();
        await _stateStore.SaveLastReportSentAsync(run.GeneratedAtUtc, cancellationToken).ConfigureAwait(false);
    }

    private static async Task<byte[]> BuildCsvAttachmentAsync(CrlCheckRun run, CancellationToken cancellationToken)
    {
        using var writer = new StringWriter(CultureInfo.InvariantCulture);
        await CsvReportFormatter.WriteAsync(writer, run, cancellationToken).ConfigureAwait(false);
        var content = writer.ToString();
        return Encoding.UTF8.GetBytes(content);
    }

    private static string BuildAttachmentName(DateTime generatedAtUtc)
    {
        return $"crl-report-{generatedAtUtc.ToUniversalTime():yyyyMMddHHmmss}.csv";
    }

    private static Summary BuildSummary(CrlCheckRun run)
    {
        return new Summary(
            run.Results.Count,
            run.Results.Count(r => string.Equals(r.Status, "OK", StringComparison.OrdinalIgnoreCase)),
            run.Results.Count(r => string.Equals(r.Status, "WARNING", StringComparison.OrdinalIgnoreCase)),
            run.Results.Count(r => string.Equals(r.Status, "EXPIRING", StringComparison.OrdinalIgnoreCase)),
            run.Results.Count(r => string.Equals(r.Status, "EXPIRED", StringComparison.OrdinalIgnoreCase)),
            run.Results.Count(r => string.Equals(r.Status, "ERROR", StringComparison.OrdinalIgnoreCase)));
    }

    private static string BuildSubject(string baseSubject, int errorCount)
    {
        if (errorCount <= 0)
        {
            return baseSubject;
        }

        return FormattableString.Invariant($"{baseSubject}: {errorCount} ERRORS");
    }

    private static string BuildPlainTextBody(CrlCheckRun run, ReportOptions options, Summary summary)
    {
        var builder = new StringBuilder();
        builder.AppendLine(FormattableString.Invariant($"Please find attached the CRL Health Report generated by Red Kestrel CrlMonitor at {FormatTimestamp(run.GeneratedAtUtc)}."));
        builder.AppendLine();
        builder.AppendLine("Summary:");
        const int valueWidth = 6;
        AppendSummaryLines(builder, summary, valueWidth);
        builder.AppendLine();
        builder.AppendLine(options.IncludeFullCsv ? "Full CSV attached." : "Full CSV attachment disabled.");
        return builder.ToString();
    }

    private static string BuildHtmlBody(CrlCheckRun run, ReportOptions options, Summary summary)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<html><body>");
        builder.AppendLine(FormattableString.Invariant($"<p>Please find attached the CRL Health Report generated by Red Kestrel CrlMonitor at {FormatTimestamp(run.GeneratedAtUtc)}.</p>"));
        builder.AppendLine("<h3>Summary</h3>");
        builder.AppendLine("<table style=\"font-family:monospace; border-collapse:collapse;\">");
        AppendSummaryRow(builder, "CRLs Checked", summary.Total, null);
        AppendSummaryRow(builder, "CRLs OK", summary.Ok, null);
        AppendSummaryRow(builder, "CRLs Warning", summary.Warning, null);
        AppendSummaryRow(builder, "CRLs Expiring", summary.Expiring, null);
        AppendSummaryRow(builder, "CRLs Expired", summary.Expired, summary.Expired > 0 ? "color:#d9534f" : null);
        AppendSummaryRow(builder, "CRLs Failed", summary.Errors, summary.Errors > 0 ? "color:#d9534f" : null);
        builder.AppendLine("</table>");
        builder.AppendLine(FormattableString.Invariant($"<p>{(options.IncludeFullCsv ? "Full CSV attached." : "Full CSV attachment disabled.")}</p>"));
        builder.AppendLine("</body></html>");
        return builder.ToString();
    }

    private static string FormatSummaryLine(string label, int value, int width)
    {
        return string.Format(CultureInfo.InvariantCulture, "{0,-25}{1," + width + "}", label, value);
    }

    private static void AppendSummaryLines(StringBuilder builder, Summary summary, int width)
    {
        builder.AppendLine(FormatSummaryLine("CRLs Checked:", summary.Total, width));
        builder.AppendLine(FormatSummaryLine("CRLs OK:", summary.Ok, width));
        builder.AppendLine(FormatSummaryLine("CRLs Warning:", summary.Warning, width));
        builder.AppendLine(FormatSummaryLine("CRLs Expiring:", summary.Expiring, width));
        builder.AppendLine(FormatSummaryLine("CRLs Expired:", summary.Expired, width));
        builder.AppendLine(FormatSummaryLine("CRLs Failed:", summary.Errors, width));
    }

    private static void AppendSummaryRow(StringBuilder builder, string label, int value, string? colorStyle)
    {
        var style = string.IsNullOrWhiteSpace(colorStyle)
            ? "text-align:right;"
            : FormattableString.Invariant($"text-align:right; {colorStyle}");
        builder.AppendLine(FormattableString.Invariant($"<tr><td style=\"padding-right:12px;\">{label}</td><td style=\"{style}\">{value}</td></tr>"));
    }

    private static string AppendHtmlLinkPlain(string body, string? url)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return body;
        }

        var builder = new StringBuilder(body);
        builder.AppendLine(FormattableString.Invariant($"View full HTML report: {url}"));
        return builder.ToString();
    }

    private static string AppendHtmlLinkHtml(string body, string? url)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return body;
        }

        var builder = new StringBuilder(body);
        var insertionIndex = body.LastIndexOf("</body>", StringComparison.OrdinalIgnoreCase);
        var linkMarkup = FormattableString.Invariant($"<p><a style=\"display:inline-block;padding:10px 18px;background:#111827;color:#fff;text-decoration:none;border-radius:8px;\" href=\"{url}\">View full HTML report</a></p>");
        if (insertionIndex >= 0)
        {
            builder.Insert(insertionIndex, linkMarkup);
        }
        else
        {
            builder.Append(linkMarkup);
        }
        return builder.ToString();
    }

    private static string FormatTimestamp(DateTime value)
    {
        return value.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss'Z'", CultureInfo.InvariantCulture);
    }

    private readonly record struct Summary(int Total, int Ok, int Warning, int Expiring, int Expired, int Errors);
}
